/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Instituto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nobu
 */
public class BuscarAlumno extends javax.swing.JFrame {
    Instituto inst;
    /**
     * Creates new form BuscarAlumno
     */
    public BuscarAlumno() {
        initComponents();
    }

    public BuscarAlumno(Instituto inst) {
        initComponents();
        this.inst = inst;
        String[] listaCarreras = inst.mostrarCarreras();
        for (int i = 0; i < listaCarreras.length; i++) {
            String[] carreraSeparada = listaCarreras[i].split(" ");
            campoCarrera.addItem(carreraSeparada[0]);
            
        }
        tablaDeRamos.setEnabled(false);
        tablaInfoAlumno.setEnabled(false);
        jPanel1.setVisible(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeRamos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInfoAlumno = new javax.swing.JTable();
        botonAtras = new javax.swing.JButton();
        campoCarrera = new javax.swing.JComboBox<>();
        botonBuscarCarrera = new javax.swing.JButton();
        campoNombreAlumno = new javax.swing.JComboBox<>();
        botonBuscarAlumno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Elegir carrera");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Elegir Alumno");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 204));

        tablaDeRamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre del Ramo", "Código del ramo", "Estado del ramo"
            }
        ));
        jScrollPane1.setViewportView(tablaDeRamos);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setWheelScrollingEnabled(false);

        tablaInfoAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "RUT", "Cantidad de creditos"
            }
        ));
        tablaInfoAlumno.setPreferredSize(new java.awt.Dimension(225, 40));
        jScrollPane2.setViewportView(tablaInfoAlumno);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        campoCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        botonBuscarCarrera.setText("Buscar");
        botonBuscarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarCarreraActionPerformed(evt);
            }
        });

        campoNombreAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        botonBuscarAlumno.setText("Buscar");
        botonBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoCarrera, 0, 320, Short.MAX_VALUE)
                            .addComponent(campoNombreAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBuscarAlumno)
                            .addComponent(botonBuscarCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonAtras)
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarCarrera))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarAlumno))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        MenuBuscar menuB = new MenuBuscar(inst);
        menuB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonBuscarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarCarreraActionPerformed
        // TODO add your handling code here:
        campoNombreAlumno.removeAllItems();
        campoNombreAlumno.addItem("");
        String nombreCarrera = campoCarrera.getSelectedItem().toString();
        String[] listaAlumnos = inst.mostrarListaAlumnos(nombreCarrera);
        
        for (int i = 0; i < listaAlumnos.length; i++) {
            String[] infoSeparada = listaAlumnos[i].split("-");
            campoNombreAlumno.addItem(infoSeparada[0]);
        }
    }//GEN-LAST:event_botonBuscarCarreraActionPerformed

    private void botonBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarAlumnoActionPerformed
        String nombreCarrera = campoCarrera.getSelectedItem().toString();
        String nombreAlumno = campoNombreAlumno.getSelectedItem().toString();
        String[] infoSeparada = inst.buscarAlumno(nombreCarrera, nombreAlumno).split("-");

        String[] listaRamos = inst.buscarRamosAlumno(nombreCarrera, nombreAlumno);
        
        if(listaRamos != null){
            DefaultTableModel tabla1 = new DefaultTableModel();
            DefaultTableModel tabla2 = new DefaultTableModel();
            tabla1.addColumn("Nombre");
            tabla1.addColumn("RUN");
            tabla1.addColumn("Cantidad de creditos");


            tabla2.addColumn("Nombre del ramo");
            tabla2.addColumn("Codigo del ramo");
            tabla2.addColumn("Estado del ramo");

            for (int i = 0; i < listaRamos.length; i++) {
                String[] infoRamoSeparada = listaRamos[i].split("-");
                tabla2.addRow(infoRamoSeparada);
            } 

            tabla1.addRow(infoSeparada);
            jPanel1.setVisible(true);
            tablaInfoAlumno.setModel(tabla1);
            tablaDeRamos.setModel(tabla2);
        }else{
            Aviso avisoEmergente = new Aviso();
            avisoEmergente.cambiarAviso("No se pudo encontrar al alumno " + nombreAlumno);
            avisoEmergente.setVisible(true);
        }
        
    }//GEN-LAST:event_botonBuscarAlumnoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBuscarAlumno;
    private javax.swing.JButton botonBuscarCarrera;
    private javax.swing.JComboBox<String> campoCarrera;
    private javax.swing.JComboBox<String> campoNombreAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaDeRamos;
    private javax.swing.JTable tablaInfoAlumno;
    // End of variables declaration//GEN-END:variables
}
