/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Instituto;

/**
 *
 * @author Nobu
 */
public class EliminarAlumno extends javax.swing.JFrame {
    Instituto inst;
    /**
     * Creates new form EliminarAlumno
     */
    public EliminarAlumno() {
        initComponents();
    }
    
    public EliminarAlumno(Instituto inst){
        initComponents();
        this.inst = inst;
        String[] listaCarreras = inst.mostrarCarreras();
        for (int i = 0; i < listaCarreras.length; i++) {
            String[] carreraSeparada = listaCarreras[i].split(" ");
            campoCarrera.addItem(carreraSeparada[0]); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonEliminarXNombre = new javax.swing.JButton();
        campoRun = new javax.swing.JTextField();
        botonEliminarXRun = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoCarrera = new javax.swing.JComboBox<>();
        campoNombre = new javax.swing.JComboBox<>();
        botonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese el nombre del alumno");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese el RUN del alumno");

        botonEliminarXNombre.setText("Eliminar");
        botonEliminarXNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarXNombreActionPerformed(evt);
            }
        });

        campoRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRunActionPerformed(evt);
            }
        });

        botonEliminarXRun.setText("Eliminar");
        botonEliminarXRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarXRunActionPerformed(evt);
            }
        });

        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("o");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese la carrera");

        campoCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        campoNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoRun)
                            .addComponent(campoCarrera, 0, 300, Short.MAX_VALUE)
                            .addComponent(campoNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonEliminarXNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonEliminarXRun, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(botonAtras))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonBuscar)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botonEliminarXNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonEliminarXRun)))
                .addGap(27, 27, 27)
                .addComponent(botonAtras)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarInformacionNombre(String nombreCarrera){
        campoNombre.removeAllItems();
        campoNombre.addItem(" ");
        String[] listaNombres = inst.mostrarListaAlumnos(nombreCarrera);
        for (int i = 0; i < listaNombres.length; i++) {
            String[] carreraSeparada = listaNombres[i].split("-");
            campoNombre.addItem(carreraSeparada[0]); 
        }
    }
    
    private void botonEliminarXNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarXNombreActionPerformed
        // TODO add your handling code here:
        String nombreCarrera = campoCarrera.getSelectedItem().toString();
        String nombreAlumno = campoNombre.getSelectedItem().toString();
        Aviso avisoEmergente = new Aviso();
        
        if(inst.eliminarAlumno(nombreAlumno, nombreCarrera)){
            avisoEmergente.cambiarAviso("Se elimino con exito al alumno " + nombreAlumno);
        }else{
            avisoEmergente.cambiarAviso("No se pudo eliminar al alumno " + nombreAlumno);
        }
        
        campoNombre.setSelectedIndex(0);        
        campoCarrera.setSelectedIndex(0);
        campoNombre.removeAllItems();
        avisoEmergente.setVisible(true);
    }//GEN-LAST:event_botonEliminarXNombreActionPerformed

    private void botonEliminarXRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarXRunActionPerformed
        // TODO add your handling code here:
        String nombreCarrera = campoCarrera.getSelectedItem().toString();
        int run = Integer.parseInt(campoRun.getText());
        Aviso avisoEmergente = new Aviso();
        
        if(inst.eliminarAlumno(run, nombreCarrera)){
            avisoEmergente.cambiarAviso("Se elimino con exito al alumno con RUN " + run);
        }else{
            avisoEmergente.cambiarAviso("No se pudo eliminar al alumno con RUN " + run);
        }
        
        avisoEmergente.setVisible(true);
        campoCarrera.setSelectedIndex(0);
        campoRun.setText("");
    }//GEN-LAST:event_botonEliminarXRunActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        MenuEliminar menuE = new MenuEliminar(inst);
        this.dispose();
        menuE.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        String nombreCarrera = campoCarrera.getSelectedItem().toString();
        actualizarInformacionNombre(nombreCarrera);
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void campoRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminarXNombre;
    private javax.swing.JButton botonEliminarXRun;
    private javax.swing.JComboBox<String> campoCarrera;
    private javax.swing.JComboBox<String> campoNombre;
    private javax.swing.JTextField campoRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
