/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Instituto;

/**
 *
 * @author Nobu
 */
public class MenuAñadir extends javax.swing.JFrame {
    private Instituto inst;
    /**
     * Creates new form MenuAñadir
     */
    public MenuAñadir() {
        initComponents();
    }
    
    public MenuAñadir(Instituto inst){
        initComponents();
        this.inst = inst;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        añadirCarrera = new javax.swing.JButton();
        matricularAlumno = new javax.swing.JButton();
        botonAñadirOpcional = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        añadirMalla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        añadirCarrera.setText("Añadir carrera");
        añadirCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirCarreraActionPerformed(evt);
            }
        });

        matricularAlumno.setText("Matricular alumno");
        matricularAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricularAlumnoActionPerformed(evt);
            }
        });

        botonAñadirOpcional.setText("Añadir ramo opcional");
        botonAñadirOpcional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirOpcionalActionPerformed(evt);
            }
        });

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        añadirMalla.setText("Añadir malla curricular");
        añadirMalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirMallaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Menu Añadir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(atras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAñadirOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matricularAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(añadirMalla, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(añadirCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(añadirCarrera)
                .addGap(18, 18, 18)
                .addComponent(añadirMalla)
                .addGap(18, 18, 18)
                .addComponent(matricularAlumno)
                .addGap(18, 18, 18)
                .addComponent(botonAñadirOpcional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(atras)
                .addGap(89, 89, 89))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menuP = new MenuPrincipal(inst);
        this.dispose();
        menuP.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void añadirCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirCarreraActionPerformed
        // TODO add your handling code here:
        AñadirCarrera aC = new AñadirCarrera(inst);
        this.dispose();
        aC.setVisible(true);
    }//GEN-LAST:event_añadirCarreraActionPerformed

    private void añadirMallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirMallaActionPerformed
        // TODO add your handling code here:
        if(!inst.contieneCarrera()){
            AñadirMalla aM = new AñadirMalla(inst);
            this.dispose();
            aM.setVisible(true);    
        }else{
            Aviso avisoEmergente = new Aviso();
            avisoEmergente.cambiarAviso("No hay carreras almacenadas para poder agregar una malla");
            avisoEmergente.setVisible(true);
        }
        
    }//GEN-LAST:event_añadirMallaActionPerformed

    private void matricularAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricularAlumnoActionPerformed
        // TODO add your handling code here:
        if(!inst.contieneCarrera() && !inst.contieneAlumnos()){
            AñadirAlumno aA = new AñadirAlumno(inst);
            this.dispose();
            aA.setVisible(true);      
        }
        else{
            Aviso avisoEmergente = new Aviso();
            avisoEmergente.cambiarAviso("No hay carreras almacenadas para poder matricular alumnos");
            avisoEmergente.setVisible(true); 
        }
    }//GEN-LAST:event_matricularAlumnoActionPerformed

    private void botonAñadirOpcionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirOpcionalActionPerformed
        if(!inst.contieneAlumnos()){
            AñadirOpcional aO = new AñadirOpcional(inst);
            this.dispose();
            aO.setVisible(true);      
        }
        else{
            Aviso avisoEmergente = new Aviso();
            avisoEmergente.cambiarAviso("No hay alumnos para poder agregar ramos opcionales");
            avisoEmergente.setVisible(true); 
        }
    }//GEN-LAST:event_botonAñadirOpcionalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton añadirCarrera;
    private javax.swing.JButton añadirMalla;
    private javax.swing.JButton botonAñadirOpcional;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton matricularAlumno;
    // End of variables declaration//GEN-END:variables
}
