/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Instituto;

/**
 *
 * @author Nobu
 */
public class MenuMostrar extends javax.swing.JFrame {
    Instituto inst;
    /**
     * Creates new form MenuMostrar
     */
    public MenuMostrar() {
        initComponents();
    }
    
    public MenuMostrar(Instituto inst){
        initComponents();
        this.inst = inst;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mostrarCarrera = new javax.swing.JButton();
        mostrarAlumnos = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonMostrarMalla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Menu Mostrar");

        mostrarCarrera.setText("Mostrar carreras");
        mostrarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCarreraActionPerformed(evt);
            }
        });

        mostrarAlumnos.setText("Mostrar alumnos");
        mostrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAlumnosActionPerformed(evt);
            }
        });

        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonMostrarMalla.setText("Mostrar Malla");
        botonMostrarMalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarMallaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mostrarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(botonMostrarMalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mostrarAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAtras)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarCarrera)
                .addGap(18, 18, 18)
                .addComponent(mostrarAlumnos)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarMalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(botonAtras)
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCarreraActionPerformed
        // TODO add your handling code here:
        MostrarCarrera mC = new MostrarCarrera(inst);
        this.dispose();
        mC.setVisible(true);
    }//GEN-LAST:event_mostrarCarreraActionPerformed

    private void mostrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAlumnosActionPerformed
        // TODO add your handling code here:
        MostrarAlumnos mA = new MostrarAlumnos(inst);
        this.dispose();
        mA.setVisible(true);
    }//GEN-LAST:event_mostrarAlumnosActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menuP = new MenuPrincipal(inst);
        this.dispose();
        menuP.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonMostrarMallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarMallaActionPerformed
        // TODO add your handling code here:
        MostrarMalla mM = new MostrarMalla(inst);
        mM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonMostrarMallaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonMostrarMalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mostrarAlumnos;
    private javax.swing.JButton mostrarCarrera;
    // End of variables declaration//GEN-END:variables
}
