/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Instituto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nobukts
 */
public class MostrarCursos extends javax.swing.JFrame {
    Instituto inst;
    /**
     * Creates new form MostrarCursos
     */
    public MostrarCursos() {
        initComponents();
    }

    public MostrarCursos(Instituto inst) {
        initComponents();
        this.inst = inst;
        DefaultTableModel tabla1 = new DefaultTableModel();
        tabla1.addColumn("Nombre del curso");
        tabla1.addColumn("Codigo del curso");
        tabla1.addColumn("Cantidad de creditos");
        tabla1.addColumn("Carrera o Escuela");
        tabla1.addColumn("Cantidad de alumnos");
        tabla1.addColumn("¿Es de primero?");
        tabla1.addColumn("¿De que tipo es?");
        
        ArrayList<String> listaCursos = inst.mostrarCursos();
        
        for (int i = 0; i < listaCursos.size(); i++) {
            String[] infoSeparada = listaCursos.get(i).split("-");
            tabla1.addRow(infoSeparada);
        }

        tablaInfo.setModel(tabla1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInfo = new javax.swing.JTable();
        botonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre del curso", "Codigo del curso", "Cantidad de creditos", "Cantidad de alumnos", "Escuela o Carrera", "¿Es de primero?", "¿De que tipo es?"
            }
        ));
        tablaInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tablaInfo);

        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(botonAtras)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAtras)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        MenuMostrar menuM = new MenuMostrar(inst);
        menuM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInfo;
    // End of variables declaration//GEN-END:variables
}
